# Generated by Django 4.1.6 on 2025-03-03 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("last_name", models.CharField(max_length=40)),
                ("first_name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
                ("iin", models.CharField(max_length=12)),
                ("school", models.CharField(max_length=40)),
                ("grade", models.IntegerField()),
                (
                    "lang",
                    models.CharField(
                        choices=[("ru", "русский"), ("kz", "казахский")], max_length=10
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("iron", "Железо"),
                            ("bronze", "Бронза"),
                            ("silver", "Серебро"),
                            ("gold", "Золото"),
                            ("plat", "Платина"),
                            ("diamond", "Бриллиант"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
