# Generated by Django 4.1.6 on 2025-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("iron", "Железо"),
                            ("bronze", "Бронза"),
                            ("silver", "Серебро"),
                            ("gold", "Золото"),
                            ("plat", "Платина"),
                            ("diamond", "Бриллиант"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.JSONField()),
            ],
        ),
    ]
