# Generated by Django 5.1.6 on 2025-03-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "Железо"),
                    ("bronze", "Бронза"),
                    ("silver", "Серебро"),
                    ("gold", "Золото"),
                    ("plat", "Платина"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "To be completed"),
                            ("rev", "Review"),
                            ("che", "Checked"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.task"
                    ),
                ),
            ],
        ),
    ]
