# Generated by Django 5.1.6 on 2025-03-03 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_task_rank_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="deadline",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission", name="essay", field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="submission", name="feedback", field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="file",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="result",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="type",
            field=models.CharField(
                choices=[("file", "File"), ("text", "Text")], max_length=10, null=True
            ),
        ),
    ]
