# Generated by Django 5.1.6 on 2025-03-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_submission_deadline_submission_essay_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission", old_name="essay", new_name="text",
        ),
    ]
