# Generated by Django 5.1.6 on 2025-03-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_essay_submission_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="file",),
    ]
