# Generated by Django 5.1.6 on 2025-03-04 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0006_remove_submission_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("last_name", models.CharField(max_length=40)),
                ("first_name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
    ]
