# Generated by Django 5.1.6 on 2025-03-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_rename_deadline_submission_assign_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission", old_name="assign_date", new_name="dedaline",
        ),
        migrations.RenameField(
            model_name="submission", old_name="subm_time", new_name="subm_date",
        ),
    ]
