# Generated by Django 5.1.6 on 2025-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_rename_dedaline_submission_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="picture",
            field=models.CharField(default="Avatar.png", max_length=40),
            preserve_default=False,
        ),
    ]
