# Generated by Django 5.1.6 on 2025-11-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_student_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "Железо"),
                    ("bronze", "Бронза"),
                    ("silver", "Серебро"),
                    ("gold", "Золото"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "Железо"),
                    ("bronze", "Бронза"),
                    ("silver", "Серебро"),
                ],
                max_length=10,
            ),
        ),
    ]
