# Generated by Django 5.1.6 on 2025-11-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_student_rank_alter_task_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=40)),
                ("short_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(model_name="student", name="school",),
        migrations.AddField(
            model_name="student",
            name="school_pointer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.school"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="school",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.school"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="school",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.school"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.school"
            ),
        ),
    ]
