# Generated by Django 5.1.6 on 2025-11-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_school_remove_student_school_student_school_pointer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="school_pointer", new_name="school",
        ),
    ]
