# Generated by Django 5.1.6 on 2025-11-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_rename_school_pointer_student_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school", old_name="full_name", new_name="name",
        ),
        migrations.RemoveField(model_name="school", name="short_name",),
    ]
