# Generated by Django 5.1.6 on 2025-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_rename_full_name_school_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="phone", field=models.CharField(max_length=20),
        ),
    ]
