# Generated by Django 4.2.26 on 2025-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_student_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="grade",),
        migrations.RemoveField(model_name="student", name="lang",),
        migrations.RemoveField(model_name="submission", name="school",),
        migrations.RemoveField(model_name="task", name="school",),
        migrations.RemoveField(model_name="teacher", name="school",),
        migrations.AddField(
            model_name="student",
            name="patronim",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student", name="phone", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "Железо"),
                    ("bronze", "Бронза"),
                    ("silver", "Серебро"),
                    ("gold", "Золото"),
                    ("plat", "Платина"),
                    ("diamond", "Бриллиант"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.CharField(default="Aqbobek Lyceum", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="rank",
            field=models.CharField(
                choices=[
                    ("iron", "Железо"),
                    ("bronze", "Бронза"),
                    ("silver", "Серебро"),
                    ("gold", "Золото"),
                    ("plat", "Платина"),
                ],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(name="School",),
    ]
