# Generated by Django 4.2.26 on 2025-12-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_student_grade_remove_student_lang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="comments",
            field=models.JSONField(default=list, null=True),
        ),
    ]
